### ISSUE TITLE
Difference between README and official documentation regarding no-byte-compile

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/auto-compile#17]
Emacs documentation explicitly recommends adding `no-byte-compile` at the end of the elisp file:

```
This is normally set in local file variables at the end of the elisp file:

;; Local Variables:
;; no-byte-compile: t
;; End:
```

But auto-compile's README suggests to do it in the very first line. Could you please explain why the difference? Is there any impact?

**Comment by tarsius** [comment]
I think both instructions just point out one way of doing it, without saying anything about that method being preferable over the other method (or even just mentioning that there is another method). And which method is described depends on what method is more convenient to describe in that context.

(I am talking about adding stuff at the beginning of the file anyway, and they probably describe the eof approach because otherwise they would have to explain that the `-*- ... -*-` *really* has to be on the first line (no the second won't work), even though you might not like `;;; foo.el --- long description -*- variables -*-`. And by the way `;;; foo.el -- bla` really has to come on the first line too. Of course *you* know that, but I have seen many packages that put one or the other on the second line.)

I don't think there is any impact, but for some variables there is. The file encoding has to be set at bof, it won't be taken into account at eof. That might be another reason why I have chosen to suggest bof - while it is not *necessary* for this variable, I feel it is somewhat similar in spirit to the encoding variable, so I picked the same place.

**Comment by DamienCassou** [comment]
I understand. Another example is `lexical-binding`.
